---
apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
spec:
  gateways:
    - {{ include "otelcol-github-actions.fullname" . }}-gateway
  hosts:
    - "{{ .Values.host }}"
  http:
    - match:
        - uri:
            prefix: "/metrics"
      route:
       - destination:
           host: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
           port:
             number: 8888
    - match:
        - uri:
            prefix: "/debug"
      route:
        - destination:
            host: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
            port:
              number: 55679
    - match:
        - uri:
            prefix: "/debug/pprof"
      route:
        - destination:
            host: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
            port:
              number: 1777
    - match:
        - uri:
            prefix: "/events" # The path needs to match GitHub App's webhook path
      route:
        - destination:
            host: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
            port:
              number: {{ include "otelcol-github-actions.receiver.port" . }}
      mirrors:
        - destination:
            host: {{ include "otelcol-github-actions.fullname" . }}-otel-collector-traces
            port:
              number: 19418
          percentage:
            value: 100
        - destination:
            host: {{ include "otelcol-github-actions.fullname" . }}-otel-annotation
            port:
              number: 33333
          percentage:
            value: 100
