---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "otelcol-github-actions.fullname" . }}-otel-collector
  labels:
  {{- include "otelcol-github-actions.labels" . | nindent 4 }}
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/whitelist-source-range: {{ include "otelcol-github-actions.ip.whitelist" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: '{{ .Values.host }}'
      http:
        paths:
          - backend:
              service:
                name: istio-gateway
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - '{{ .Values.host }}'
      secretName: otel-collector-tls
---
apiVersion: v1
kind: Service
metadata:
  name: istio-gateway
spec:
  type: ExternalName
  externalName: istio-gateway.istio-system.svc.cluster.local
