---
name: issue-2211
on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.59.0"
      - name: Update
        run: |
          updatecli update --config ./issue-2211
