---
name: issue-2211
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.77.0"
      - name: Set environment variables
        run: |
          echo "GIT_USER=updatecli" >> $GITHUB_ENV
          echo "GIT_EMAIL=updatecli@example.com" >> $GITHUB_ENV
          echo "GITHUB_OWNER=kuisathaverat" >> $GITHUB_ENV
          echo "GITHUB_REPO=updatecli-issues" >> $GITHUB_ENV
          echo "GIT_USER=updatecli" >> $GITHUB_ENV

      - name: Update
        run: |
          for channel in "01" "02"; do
            export UPDATE_CHANNEL="${channel}"
            updatecli apply --config ./issue-2211/test.yml
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUN_NUMBER: ${{ github.run_number }}
