---
name: new-helm-template
on:
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: "Setup updatecli"
        uses: "updatecli/updatecli-action@v2.75.0"
      - name: Update
        run: updatecli apply --config ./new-helm-template/test.yml --debug
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_USER: updatecli
          GIT_EMAIL: updatecli@example.com
          GITHUB_OWNER: kuisathaverat
          GITHUB_REPO: updatecli-issues

